[package]
name = "bottle-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.7.1"
tar = "0.4"
structopt = "0.3"
